### ISSUE TITLE
how to use get_page properly

### ISSUE THREAD

**Issue by digitxo** [PI-Media/json-api#3]
I'd like to use get_page to query the users/me page. how do i do this?

**Comment by pimedia** [comment]
Use the /api/user/get_userinfo/?user_id=1and / or /api/user/get_user_meta/?cookie=COOKIE-HERE&meta_key=KEY-HERE 
    On Friday, December 20, 2019, 04:37:56 AM GMT+5, digitxo <notifications@github.com> wrote:  
 
 
I'd like to use get_page to query the users/me page. how do i do this?

**Comment by digitxo** [comment]
Ok. I have a webpage 

https://balancingpawsdogtraining.com/users-page/digit/

where digit is the username of the user, how can i access this page with this library?

**Comment by pimedia** [comment]
first install the JSON API plugin, then install JSON API User plugin 
then enable the User controller from WordPress > Settings > JSON API >
Then from User controller, click on get_userinfo and provide parameter 
    On Friday, December 20, 2019, 10:10:06 PM GMT+5, digitxo <notifications@github.com> wrote:  
 
 
Ok. I have a webpage

https://balancingpawsdogtraining.com/users-page/digit/

where digit is the username of the user, how can i access this page with this library?

**Comment by digitxo** [comment]
Hi.. https://balancingpawsdogtraining.com/api/user/get_userinfo/?user_id=1 <- this isn't what I'm looking for.


My website makes the following page available 
https://balancingpawsdogtraining.com/users-page/digit/

When logged in.

I'd like to GET that page from Postman.

Is this possible?

**Comment by digitxo** [comment]
I just did some research and i can acess the page via https://balancingpawsdogtraining.com/api/get_page/?id=XXX

But, I have one more question.

How can I find the ID of the page dynamically?

**Comment by pimedia** [comment]
you should call the slug, thats easier. you don't need to find id.
but if you must call by id, then you can call the /api/get_page_index/ to get list of all pages
    On Friday, December 20, 2019, 10:43:10 PM GMT+5, digitxo <notifications@github.com> wrote:  
 
 
I just did some research and i can acess the page via https://balancingpawsdogtraining.com/api/get_page/?id=XXX

But, I have one more question.

How can I find the ID of the page dynamically?

**Comment by digitxo** [comment]
I get the error "{"status":"error","error":"Not found."}" When I put in the slug?

**Comment by pimedia** [comment]
please scroll down and  follow the documentation here for all endpoints: https://github.com/PI-Media/json-api
    On Friday, December 20, 2019, 10:51:30 PM GMT+5, digitxo <notifications@github.com> wrote:  
 
 
I get the error "{"status":"error","error":"Not found."}" When I put in the slug?

**Comment by digitxo** [comment]
Hmm.. no not working ---
https://balancingpawsdogtraining.com/api/get_page/?id=1226

See this page, the "slug" is "digit"

https://balancingpawsdogtraining.com/api/get_page/?slug=digit

isn't working.

**Comment by pimedia** [comment]
![Screen Shot 2019-12-21 at 4 14 31 PM](https://user-images.githubusercontent.com/927225/71307226-1133be80-240d-11ea-845c-9a08d679a9da.png)

https://balancingpawsdogtraining.com/api/get_page/?id=1226

works for me.
