### ISSUE TITLE
help with installed json api

### ISSUE THREAD

**Issue by justinmcnaughton** [PI-Media/json-api#4]
![image](https://user-images.githubusercontent.com/59097142/71280762-6393b300-2319-11ea-8007-48006dc5d53a.png)

Getting this messsage, I don't know what I'm doing perhaps, but I think i've installed everything.  I go to that link and it's just a bunch of stuff on github.  I need easy, clean install and activate or i'm lost.

Pls help

![image](https://user-images.githubusercontent.com/59097142/71280816-845c0880-2319-11ea-8af0-a36289df5ab0.png)

**Comment by pimedia** [comment]
1. Please download the zip file from the link as shown in the screenshot. 2. upload the zip file in wordpress as new plugin. Activate and that's it.
You can access the Settings > JSON API
    On Friday, December 20, 2019, 11:12:04 PM GMT+5, justinmcnaughton <notifications@github.com> wrote:  
 
 


Getting this messsage, I don't know what I'm doing perhaps, but I think i've installed everything. I go to that link and it's just a bunch of stuff on github. I need easy, clean install and activate or i'm lost.

Pls help

**Comment by pimedia** [comment]
![Screen Shot 2019-12-20 at 11 18 04 PM](https://user-images.githubusercontent.com/927225/71281346-793bc380-237f-11ea-95cd-d66c56ac4b4b.png)
