### ISSUE TITLE
Nonce required on register api/user/register

### ISSUE THREAD

**Issue by habib-it** [PI-Media/json-api#42]
"error": "Invalid access, unverifiable 'nonce' value. Use the 'get_nonce' Core API method. "

I am trying to call register api
https://example.com/api/user/register

it is asking me nonce var is required and when i tried to get it from this url
https://example.com/api/get_nonce/?controller=core&method=get_nonce
i put this nonce it register api, then it gives unverifiable 'nonce' value error.

Can you please guide.

It would be great, thanks.

**Comment by habib-it** [comment]
sorry i was calling wrong api as mentioned in register api response

here is the correct cone
https://lexample.com/api/get_nonce/?controller=user&method=register

**Comment by habib-it** [comment]
sorry i was calling wrong api as mentioned in register api response

here is the correct cone
https://lexample.com/api/get_nonce/?controller=user&method=register

**Comment by pimedia** [comment]
You have to use like this https://example.com/api/get_nonce/?controller=user&method=register
    On Monday, October 2, 2023 at 02:56:14 PM GMT+5, habib-it ***@***.***> wrote:  
 
 


"error": "Invalid access, unverifiable 'nonce' value. Use the 'get_nonce' Core API method. "

I am trying to call register api
https://example.com/api/user/register

it is asking me nonce var is required and when i tried to get it from this url
https://example.com/api/get_nonce/?controller=core&method=get_nonce
i put this nonce it register api, then it gives unverifiable 'nonce' value error.

Can you please guide.

It would be great, thanks.
